name = input("Введите ваше имя")
sur_name = input("Введите вашу фамилю")
group = input("Ввидите номер группы")
city = input("Из какого вы города ?")
age = int(input("Сколько вам полных лет?"))
age = min(max(age, 1), 120)
favorite_subject = input("Какой ваш люьимый предмет ?")
hours = float(input("Сколько часов вы готовы выделять на обучение ?"))
average_time_per_day = hours / 7
print("Карточка студента")
print(f"имя: {name}")
print(f"фамилия: {sur_name}")
print((f"Через 4 недели вы потратите {hours * 4:.2f} часов."))
print(f"Среднне время учебы за день{average_time_per_day:.2f}")
